DPCPP_CXX = dpcpp
DPCPP_CXXFLAGS = /Zi /EHsc
DPCPP_LDFLAGS = 
DPCPP_EXE_NAME = matrix_mul_sycl.exe
DPCPP_SOURCES = src/matrix_mul_sycl.cpp

all:
	$(DPCPP_CXX) $(DPCPP_CXXFLAGS) -o $(DPCPP_EXE_NAME) $(DPCPP_SOURCES) $(DPCPP_LDFLAGS)

build_sycl:
	$(DPCPP_CXX) $(DPCPP_CXXFLAGS) -o $(DPCPP_EXE_NAME) $(DPCPP_SOURCES) $(DPCPP_LDFLAGS)


run:
	$(DPCPP_EXE_NAME)

run_sycl:
	$(DPCPP_EXE_NAME)


clean: 
	del -rf $(DPCPP_EXE_NAME) *.pdb
