[project]
name = "intelpython-daal4py-distributedlinearregression"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "joblib>=1.4.2",
    "numpy==1.26.4",
    "pandas>=2.2.3",
]
