if(NOT DEFINED MKLROOT)
  find_file(MKL_DIR
    NAMES
      mkl
    HINTS
      $ENV{ONEAPI_ROOT}
    NO_DEFAULT_PATH
    )
  set(MKLROOT ${MKL_DIR}/latest)
endif()
if(NOT DEFINED TBBROOT)
  find_file(TBB_DIR
    NAMES
      tbb
    HINTS
      $ENV{ONEAPI_ROOT}
    NO_DEFAULT_PATH
    )
  set(TBBROOT ${TBB_DIR}/latest)
endif()
if(NOT DEFINED DEVUTILITIESROOT)
  find_file(DEVUTILITIES_DIR
    NAMES
      dev-utilities
    HINTS
      $ENV{ONEAPI_ROOT}
    NO_DEFAULT_PATH
    )
  set(DEVUTILITIESROOT ${DEVUTILITIES_DIR}/latest)
endif()

if(NOT DEFINED MKL_LIBRARY_DIR)
  set(MKL_LIBRARY_DIR ${MKLROOT}/lib/intel64)
endif()
if(NOT DEFINED MKL_INCLUDE_DIR)
  set(MKL_INCLUDE_DIR ${MKLROOT}/include)
endif()
if(NOT DEFINED TBB_LIBRARY_DIR)
  set(TBB_LIBRARY_DIR ${TBBROOT}/lib/intel64/gcc4.8)
endif()
if(NOT DEFINED TBB_INCLUDE_DIR)
  set(TBB_INCLUDE_DIR ${TBBROOT}/include)
endif()
if(NOT DEFINED DEVUTILITIES_INCLUDE_DIR)
  set(DEVUTILITIES_INCLUDE_DIR ${DEVUTILITIESROOT}/include)
endif()
