SYCL_CXX = icx-cl
SYCL_CXXFLAGS = -fsycl /Zi /EHsc
SYCL_LDFLAGS =
SYCL_EXE_NAME = matrix_mul_sycl.exe
SYCL_SOURCES = src/matrix_mul_sycl.cpp

all:
	$(SYCL_CXX) $(SYCL_CXXFLAGS) -o $(SYCL_EXE_NAME) $(SYCL_SOURCES) $(SYCL_LDFLAGS)

build_sycl:
	$(SYCL_CXX) $(SYCL_CXXFLAGS) -o $(SYCL_EXE_NAME) $(SYCL_SOURCES) $(SYCL_LDFLAGS)


run:
	$(SYCL_EXE_NAME)

run_sycl:
	$(SYCL_EXE_NAME)

clean:
	del -rf $(SYCL_EXE_NAME) *.pdb
