[project]
name = "intel-extension-for-sklearn-performance-svc-adult"
version = "0.1.0"
description = "Use Intel(R) Extension for Scikit-learn to accelerate the training and prediction with SVC algorithm on Adult dataset. Compare the performance of SVC algorithm optimized through Intel(R) Extension for Scikit-learn against original Scikit-learn."
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}

authors = [
    {name = "Copyright © 2023 Intel Corporation"}
]
dependencies = [
    "notebook>=7.3.2,<8.0.0",
    "matplotlib>=3.10.1,<4.0.0",
    "scikit-learn>=1.6.1,<2.0.0",
    "scikit-learn-intelex>=2025.2.0,<2026.0.0",
]

[project.scripts]
python-validate = "Intel_Extension_for_SKLearn_Performance_SVC_Adult:main"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
