all: prog1 prog2 prog3 prog4 prog5 prog6 prog7 prog8 prog9 prog10 prog11 prog12 prog13 prog14 prog15 prog16 prog17 prog18 prog19 prog20 prog21 prog22 prog23 prog24 prog25 prog26 prog27 prog28 prog29 prog30 prog31 prog32

prog1: 01_oneAPI_Intro/lab/simple.cpp
	dpcpp -o 01_oneAPI_Intro/bin/prog1 01_oneAPI_Intro/lab/simple.cpp

prog2: 01_oneAPI_Intro/lab/simple-vector-incr.cpp
	dpcpp -o 01_oneAPI_Intro/bin/prog2 01_oneAPI_Intro/lab/simple-vector-incr.cpp

prog3: 02_DPCPP_Program_Structure/lab/buffer_sample.cpp
	dpcpp -o 02_DPCPP_Program_Structure/bin/prog3 02_DPCPP_Program_Structure/lab/buffer_sample.cpp 
    
prog4: 02_DPCPP_Program_Structure/lab/buffer_destruction2.cpp
	dpcpp -o 02_DPCPP_Program_Structure/bin/prog4 02_DPCPP_Program_Structure/lab/buffer_destruction2.cpp
    
prog5: 02_DPCPP_Program_Structure/lab/custom_device_sample.cpp
	dpcpp -o 02_DPCPP_Program_Structure/bin/prog5 02_DPCPP_Program_Structure/lab/custom_device_sample.cpp

prog6: 02_DPCPP_Program_Structure/src/complex_mult_solution.cpp 
	dpcpp  -g -o 02_DPCPP_Program_Structure/bin/prog6 02_DPCPP_Program_Structure/src/complex_mult_solution.cpp -I02_DPCPP_Program_Structure/src/

prog7: 03_DPCPP_Unified_Shared_Memory/lab/usm.cpp
	dpcpp -o 03_DPCPP_Unified_Shared_Memory/prog7 03_DPCPP_Unified_Shared_Memory/lab/usm.cpp

prog8: 03_DPCPP_Unified_Shared_Memory/lab/usm_data.cpp
	dpcpp -o 03_DPCPP_Unified_Shared_Memory/prog8 03_DPCPP_Unified_Shared_Memory/lab/usm_data.cpp

prog9: 03_DPCPP_Unified_Shared_Memory/src/usm_data2.cpp
	dpcpp -o 03_DPCPP_Unified_Shared_Memory/prog9 03_DPCPP_Unified_Shared_Memory/src/usm_data2.cpp
prog10: 03_DPCPP_Unified_Shared_Memory/src/usm_explicit.cpp
	dpcpp -o 03_DPCPP_Unified_Shared_Memory/prog10 03_DPCPP_Unified_Shared_Memory/src/usm_explicit.cpp

prog11: 04_DPCPP_Sub_Groups/lab/sub_group_info.cpp
	dpcpp -o 04_DPCPP_Sub_Groups/prog11 04_DPCPP_Sub_Groups/lab/sub_group_info.cpp

prog12: 04_DPCPP_Sub_Groups/lab/sub_group_shuffle.cpp
	dpcpp -o 04_DPCPP_Sub_Groups/prog12 04_DPCPP_Sub_Groups/lab/sub_group_shuffle.cpp
prog13: 04_DPCPP_Sub_Groups/lab/sub_group_collective.cpp
	dpcpp -o 04_DPCPP_Sub_Groups/prog13 04_DPCPP_Sub_Groups/lab/sub_group_collective.cpp

prog14: 07_DPCPP_Library/lab/binary_search.cpp
	dpcpp -o 07_DPCPP_Library/bin/prog14 07_DPCPP_Library/lab/binary_search.cpp

prog15: 07_DPCPP_Library/lab/lower_bound.cpp
	dpcpp -o 07_DPCPP_Library/bin/prog15 07_DPCPP_Library/lab/lower_bound.cpp

prog16: 07_DPCPP_Library/lab/upper_bound.cpp
	dpcpp -o 07_DPCPP_Library/bin/prog16 07_DPCPP_Library/lab/upper_bound.cpp

prog17: 07_DPCPP_Library/lab/exclusive_scan.cpp
	dpcpp -o 07_DPCPP_Library/bin/prog17 07_DPCPP_Library/lab/exclusive_scan.cpp

prog18: 07_DPCPP_Library/lab/inclusive_scan.cpp
	dpcpp -o 07_DPCPP_Library/bin/prog18 07_DPCPP_Library/lab/inclusive_scan.cpp

prog19: 07_DPCPP_Library/lab/reduce_segment.cpp
	dpcpp -o 07_DPCPP_Library/bin/prog19 07_DPCPP_Library/lab/reduce_segment.cpp

prog20: 07_DPCPP_Library/lab/dpl_buffer.cpp
	dpcpp -o 07_DPCPP_Library/bin/prog20 07_DPCPP_Library/lab/dpl_buffer.cpp

prog21: 07_DPCPP_Library/lab/dpl_simple.cpp
	dpcpp -o 07_DPCPP_Library/bin/prog21 07_DPCPP_Library/lab/dpl_simple.cpp

prog22: 07_DPCPP_Library/lab/dpl_sortdouble.cpp
	dpcpp -o 07_DPCPP_Library/bin/prog22 07_DPCPP_Library/lab/dpl_sortdouble.cpp

prog23: 07_DPCPP_Library/lab/dpl_usm_alloc.cpp
	dpcpp -o 07_DPCPP_Library/bin/prog23 07_DPCPP_Library/lab/dpl_usm_alloc.cpp

prog24: 07_DPCPP_Library/lab/dpl_usm_pointer.cpp
	dpcpp -o 07_DPCPP_Library/bin/prog24 07_DPCPP_Library/lab/dpl_usm_pointer.cpp

prog25: 07_DPCPP_Library/lab/counting_iterator.cpp
	dpcpp -o 07_DPCPP_Library/bin/prog25 07_DPCPP_Library/lab/counting_iterator.cpp

prog26: 07_DPCPP_Library/lab/zip_iterator.cpp
	dpcpp -o 07_DPCPP_Library/bin/prog26 07_DPCPP_Library/lab/zip_iterator.cpp

prog27: 07_DPCPP_Library/lab/transform_iterator.cpp
	dpcpp -o 07_DPCPP_Library/bin/prog27 07_DPCPP_Library/lab/transform_iterator.cpp

prog28: 07_DPCPP_Library/lab/discard_iterator.cpp
	dpcpp -o 07_DPCPP_Library/bin/prog28 07_DPCPP_Library/lab/discard_iterator.cpp

prog29: 07_DPCPP_Library/lab/permutation_iterator.cpp
	dpcpp -o 07_DPCPP_Library/bin/prog29 07_DPCPP_Library/lab/permutation_iterator.cpp

prog30: 07_DPCPP_Library/lab/ranges.cpp
	dpcpp -o 07_DPCPP_Library/bin/prog30 07_DPCPP_Library/lab/ranges.cpp

prog31: 07_DPCPP_Library/lab/maximum_function.cpp
	dpcpp -o 07_DPCPP_Library/bin/prog31 07_DPCPP_Library/lab/maximum_function.cpp

prog32: 07_DPCPP_Library/lab/minimum_function.cpp
	dpcpp -o 07_DPCPP_Library/bin/prog32 07_DPCPP_Library/lab/minimum_function.cpp



#Run: prog1 prog2 prog3 prog4 prog5 prog6 prog7 prog8 prog9 prog10 prog11 prog12 prog13 prog12 prog13 prog14 prog15 prog16 prog17 prog18 prog19 prog20 prog21 prog22 prog23 prog24 prog25 prog26 prog27 prog28 prog29 prog30 prog31 prog32

Run:
	01_oneAPI_Intro/bin/prog1
	01_oneAPI_Intro/bin/prog2	
	02_DPCPP_Program_Structure/bin/prog3
	02_DPCPP_Program_Structure/bin/prog4
	02_DPCPP_Program_Structure/bin/prog5
	02_DPCPP_Program_Structure/bin/prog6
	03_DPCPP_Unified_Shared_Memory/prog7
	03_DPCPP_Unified_Shared_Memory/prog8
	03_DPCPP_Unified_Shared_Memory/prog9
	03_DPCPP_Unified_Shared_Memory/prog10
	04_DPCPP_Sub_Groups/prog11
	04_DPCPP_Sub_Groups/prog12
	04_DPCPP_Sub_Groups/prog13
	07_DPCPP_Library/bin/prog14
	07_DPCPP_Library/bin/prog15
	07_DPCPP_Library/bin/prog16
	07_DPCPP_Library/bin/prog17
	07_DPCPP_Library/bin/prog18
	07_DPCPP_Library/bin/prog19
	07_DPCPP_Library/bin/prog20
	07_DPCPP_Library/bin/prog21
	07_DPCPP_Library/bin/prog22
	07_DPCPP_Library/bin/prog23
	07_DPCPP_Library/bin/prog24
	07_DPCPP_Library/bin/prog25
	07_DPCPP_Library/bin/prog26
	07_DPCPP_Library/bin/prog27
	07_DPCPP_Library/bin/prog28
	07_DPCPP_Library/bin/prog29
	07_DPCPP_Library/bin/prog30
	07_DPCPP_Library/bin/prog31
	07_DPCPP_Library/bin/prog32

clean:
	rm -rf 01_oneAPI_Intro/bin/prog1 01_oneAPI_Intro/bin/prog2 02_DPCPP_Program_Structure/bin/prog3 02_DPCPP_Program_Structure/bin/prog4 02_DPCPP_Program_Structure/bin/prog5 02_DPCPP_Program_Structure/bin/prog6 03_DPCPP_Unified_Shared_Memory/prog7 03_DPCPP_Unified_Shared_Memory/prog8 03_DPCPP_Unified_Shared_Memory/prog9 03_DPCPP_Unified_Shared_Memory/prog10 04_DPCPP_Sub_Groups/prog11 04_DPCPP_Sub_Groups/prog12 04_DPCPP_Sub_Groups/prog13 07_DPCPP_Library/bin/prog14 07_DPCPP_Library/bin/prog15 07_DPCPP_Library/bin/prog16 07_DPCPP_Library/bin/prog17 07_DPCPP_Library/bin/prog18 07_DPCPP_Library/bin/prog19 07_DPCPP_Library/bin/prog20 07_DPCPP_Library/bin/prog21 07_DPCPP_Library/bin/prog22 07_DPCPP_Library/bin/prog23 07_DPCPP_Library/bin/prog24 07_DPCPP_Library/bin/prog25 07_DPCPP_Library/bin/prog26 07_DPCPP_Library/bin/prog27 07_DPCPP_Library/bin/prog28 07_DPCPP_Library/bin/prog29 07_DPCPP_Library/bin/prog30 07_DPCPP_Library/bin/prog31 07_DPCPP_Library/bin/prog32
