all: prog1 prog2 prog3 prog4 prog5 prog6 prog8 prog9 prog10


prog1: AI_Kit_XGBoost_Predictive_Modeling/00_Local_Setup/Local_Setup.ipynb
	jupyter nbconvert --to script AI_Kit_XGBoost_Predictive_Modeling/00_Local_Setup/Local_Setup.ipynb

prog2: AI_Kit_XGBoost_Predictive_Modeling/01_Decision_Trees/Decision_Trees.ipynb
	jupyter nbconvert --to script AI_Kit_XGBoost_Predictive_Modeling/01_Decision_Trees/Decision_Trees.ipynb

prog3: AI_Kit_XGBoost_Predictive_Modeling/02_Bagging/Bagging_RF.ipynb
	jupyter nbconvert --to script AI_Kit_XGBoost_Predictive_Modeling/02_Bagging/Bagging_RF.ipynb
	
prog4: AI_Kit_XGBoost_Predictive_Modeling/03_XGBoost/XGBoost.ipynb
	jupyter nbconvert --to script AI_Kit_XGBoost_Predictive_Modeling/03_XGBoost/XGBoost.ipynb
    
prog5: AI_Kit_XGBoost_Predictive_Modeling/04_oneDal/XGBoost-oneDal.ipynb
	jupyter nbconvert --to script AI_Kit_XGBoost_Predictive_Modeling/04_oneDal/XGBoost-oneDal.ipynb

prog6: AI_Kit_XGBoost_Predictive_Modeling.complete/00_Local_Setup/Local_Setup.ipynb
	jupyter nbconvert --to script AI_Kit_XGBoost_Predictive_Modeling.complete/00_Local_Setup/Local_Setup.ipynb

prog7: AI_Kit_XGBoost_Predictive_Modeling.complete/01_Decision_Trees/Decision_Trees.ipynb
	jupyter nbconvert --to script AI_Kit_XGBoost_Predictive_Modeling.complete/01_Decision_Trees/Decision_Trees.ipynb

prog8: AI_Kit_XGBoost_Predictive_Modeling.complete/02_Bagging/Bagging_RF.ipynb
	jupyter nbconvert --to script AI_Kit_XGBoost_Predictive_Modeling.complete/02_Bagging/Bagging_RF.ipynb
	
prog9: AI_Kit_XGBoost_Predictive_Modeling.complete/03_XGBoost/XGBoost.ipynb
	jupyter nbconvert --to script AI_Kit_XGBoost_Predictive_Modeling.complete/03_XGBoost/XGBoost.ipynb
    
prog10: AI_Kit_XGBoost_Predictive_Modeling.complete/04_oneDal/XGBoost-oneDal.ipynb
	jupyter nbconvert --to script AI_Kit_XGBoost_Predictive_Modeling.complete/04_oneDal/XGBoost-oneDal.ipynb

