[project]
name = "inc-sample-for-tensorflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flatbuffers>=25.2.10",
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.1",
    "neural-compressor>=3.3",
    "notebook>=7.3.2",
    "runipy>=0.1.5",
]
