all: prog1 prog2 prog3 prog4 prog5 prog6 prog8 prog9 prog10 prog11 


	
prog1: 01_Introduction_to_Machine_Learning_and_Tools/Introduction_to_Machine_Learning_and_Toolkit-ANSWERS.ipynb
	jupyter nbconvert --to script 01_Introduction_to_Machine_Learning_and_Tools/Introduction_to_Machine_Learning_and_Toolkit-ANSWERS.ipynb
	mv 01_Introduction_to_Machine_Learning_and_Tools/Introduction_to_Machine_Learning_and_Toolkit-ANSWERS.py  01_Introduction_to_Machine_Learning_and_Tools/Introduction_to_Machine_Learning_and_Toolkit-ANSWERS.ipy
	cd 01_Introduction_to_Machine_Learning_and_Tools/; ipython Introduction_to_Machine_Learning_and_Toolkit-ANSWERS.ipy


prog2: 02-Supervised_Learning_and_K_Nearest_Neighbors/Supervised_Learning_and_K_Nearest_Neighbors_Exercises-ANSWERS.ipynb
	jupyter nbconvert --to script 02-Supervised_Learning_and_K_Nearest_Neighbors/Supervised_Learning_and_K_Nearest_Neighbors_Exercises-ANSWERS.ipynb
	mv 02-Supervised_Learning_and_K_Nearest_Neighbors/Supervised_Learning_and_K_Nearest_Neighbors_Exercises-ANSWERS.py  02-Supervised_Learning_and_K_Nearest_Neighbors/Supervised_Learning_and_K_Nearest_Neighbors_Exercises-ANSWERS.ipy
	cd 02-Supervised_Learning_and_K_Nearest_Neighbors/; ipython Supervised_Learning_and_K_Nearest_Neighbors_Exercises-ANSWERS.ipy

prog3: 03-Train_Test_Splits_Validation_Linear_Regression/Train_Test_Splits_Validation_Linear_Regression-ANSWERS.ipynb
	jupyter nbconvert --to script 03-Train_Test_Splits_Validation_Linear_Regression/Train_Test_Splits_Validation_Linear_Regression-ANSWERS.ipynb
	mv 03-Train_Test_Splits_Validation_Linear_Regression/Train_Test_Splits_Validation_Linear_Regression-ANSWERS.py  03-Train_Test_Splits_Validation_Linear_Regression/Train_Test_Splits_Validation_Linear_Regression-ANSWERS.ipy
	cd 03-Train_Test_Splits_Validation_Linear_Regression/; ipython Train_Test_Splits_Validation_Linear_Regression-ANSWERS.ipy
	
prog4: 04-Regularization_and_Gradient_Descent/Regularization_and_Gradient_Descent_Exercises-ANSWERS.ipynb
	jupyter nbconvert --to script 04-Regularization_and_Gradient_Descent/Regularization_and_Gradient_Descent_Exercises-ANSWERS.ipynb
	mv 04-Regularization_and_Gradient_Descent/Regularization_and_Gradient_Descent_Exercises-ANSWERS.py  04-Regularization_and_Gradient_Descent/Regularization_and_Gradient_Descent_Exercises-ANSWERS.ipy
	cd 04-Regularization_and_Gradient_Descent/; ipython Regularization_and_Gradient_Descent_Exercises-ANSWERS.ipy
    
prog5: 05-Logistic_Regression_and_Classification_Error_Metrics/Logistic_Regression_and_Classification_Error_Metrics_Exercises-ANSWERS.ipynb
	jupyter nbconvert --to script 05-Logistic_Regression_and_Classification_Error_Metrics/Logistic_Regression_and_Classification_Error_Metrics_Exercises-ANSWERS.ipynb
	mv 05-Logistic_Regression_and_Classification_Error_Metrics/Logistic_Regression_and_Classification_Error_Metrics_Exercises-ANSWERS.py  05-Logistic_Regression_and_Classification_Error_Metrics/Logistic_Regression_and_Classification_Error_Metrics_Exercises-ANSWERS.ipy
	cd 05-Logistic_Regression_and_Classification_Error_Metrics/; ipython Logistic_Regression_and_Classification_Error_Metrics_Exercises-ANSWERS.ipy

prog6: 06-SVM_and_Kernels/SVM_Kernels_Exercises-ANSWERS.ipynb
	jupyter nbconvert --to script 06-SVM_and_Kernels/SVM_Kernels_Exercises-ANSWERS.ipynb
	mv 06-SVM_and_Kernels/SVM_Kernels_Exercises-ANSWERS.py  06-SVM_and_Kernels/SVM_Kernels_Exercises-ANSWERS.ipy
	cd 06-SVM_and_Kernels/; ipython SVM_Kernels_Exercises-ANSWERS.ipy

prog7: 07-Decision_Trees/Decision_Trees_Exercises-ANSWERS.ipynb
	jupyter nbconvert --to script 07-Decision_Trees/Decision_Trees_Exercises-ANSWERS.ipynb
	mv 07-Decision_Trees/Decision_Trees_Exercises-ANSWERS.py  07-Decision_Trees/Decision_Trees_Exercises-ANSWERS.ipy
	cd 07-Decision_Trees/; ipython Decision_Trees_Exercises-ANSWERS.ipy

prog8: 08-Bagging/Bagging_Exercises-ANSWERS.ipynb
	jupyter nbconvert --to script 08-Bagging/Bagging_Exercises-ANSWERS.ipynb
	mv 08-Bagging/Bagging_Exercises-ANSWERS.py  08-Bagging/Bagging_Exercises-ANSWERS.ipy
	cd 08-Bagging/; ipython Bagging_Exercises-ANSWERS.ipy
	
prog9: 09-Boosting_and_Stacking/Boosting_and_Stacking_Exercises-ANSWERS.ipynb
	jupyter nbconvert --to script 09-Boosting_and_Stacking/Boosting_and_Stacking_Exercises-ANSWERS.ipynb
	mv 09-Boosting_and_Stacking/Boosting_and_Stacking_Exercises-ANSWERS.py  09-Boosting_and_Stacking/Boosting_and_Stacking_Exercises-ANSWERS.ipy
	cd 09-Boosting_and_Stacking/; ipython Boosting_and_Stacking_Exercises-ANSWERS.ipy

prog10: 10-Introduction_to_Unsupervised_Learning_and_Clustering_Methods/Clustering_Methods_Exercises-ANSWERS.ipynb
	jupyter nbconvert --to script 10-Introduction_to_Unsupervised_Learning_and_Clustering_Methods/Clustering_Methods_Exercises-ANSWERS.ipynb
	mv 10-Introduction_to_Unsupervised_Learning_and_Clustering_Methods/Clustering_Methods_Exercises-ANSWERS.py  10-Introduction_to_Unsupervised_Learning_and_Clustering_Methods/Clustering_Methods_Exercises-ANSWERS.ipy
	cd 10-Introduction_to_Unsupervised_Learning_and_Clustering_Methods/; ipython Clustering_Methods_Exercises-ANSWERS.ipy
	
prog11: 11-Dimensionality_Reduction_and_Advanced_Topics/Dimensionality_Reduction_Exercises-ANSWERS.ipynb
	jupyter nbconvert --to script 11-Dimensionality_Reduction_and_Advanced_Topics/Dimensionality_Reduction_Exercises-ANSWERS.ipynb
	mv 11-Dimensionality_Reduction_and_Advanced_Topics/Dimensionality_Reduction_Exercises-ANSWERS.py  11-Dimensionality_Reduction_and_Advanced_Topics/Dimensionality_Reduction_Exercises-ANSWERS.ipy
	cd 11-Dimensionality_Reduction_and_Advanced_Topics/; ipython Dimensionality_Reduction_Exercises-ANSWERS.ipy

