# TCL File Generated by Component Editor 23.2
# Fri Aug 04 08:02:03 PDT 2023
# DO NOT MODIFY


# 
# oneAPI_axi4s_gasket "oneAPI AXI4-Stream Input Gasket" v0.3
# Paul White 2023.08.04.08:02:03
# Allow a oneAPI IP component to communicate with a VVP IP
# 

# 
# request TCL package from ACDS 23.2
# 
package require -exact qsys 23.2


# 
# module oneAPI_axi4s_gasket
# 
set_module_property DESCRIPTION "Allow a oneAPI IP component to communicate with a VVP IP"
set_module_property NAME oneAPI_axi4s_gasket
set_module_property VERSION 0.3
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP oneAPI
set_module_property AUTHOR "Paul White"
set_module_property DISPLAY_NAME "oneAPI AXI4-Stream Input Gasket"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0
set_module_property PRE_COMP_MODULE_ENABLED false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL axi_to_avalon_gasket
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file axi_to_avst_gasket.sv SYSTEM_VERILOG PATH axi_to_avst_gasket.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""
set_interface_property clock IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property clock SV_INTERFACE_TYPE ""
set_interface_property clock SV_INTERFACE_MODPORT_TYPE ""

add_interface_port clock clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""
set_interface_property reset_sink IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property reset_sink SV_INTERFACE_TYPE ""
set_interface_property reset_sink SV_INTERFACE_MODPORT_TYPE ""

add_interface_port reset_sink resetn reset_n Input 1


# 
# connection point axi4stream_slave
# 
add_interface axi4stream_slave axi4stream end
set_interface_property axi4stream_slave associatedClock clock
set_interface_property axi4stream_slave associatedReset reset_sink
set_interface_property axi4stream_slave ENABLED true
set_interface_property axi4stream_slave EXPORT_OF ""
set_interface_property axi4stream_slave PORT_NAME_MAP ""
set_interface_property axi4stream_slave CMSIS_SVD_VARIABLES ""
set_interface_property axi4stream_slave SVD_ADDRESS_GROUP ""
set_interface_property axi4stream_slave IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property axi4stream_slave SV_INTERFACE_TYPE ""
set_interface_property axi4stream_slave SV_INTERFACE_MODPORT_TYPE ""

add_interface_port axi4stream_slave axi_rx_tready tready Output 1
add_interface_port axi4stream_slave axi_rx_tvalid tvalid Input 1
add_interface_port axi4stream_slave axi_rx_tdata tdata Input 64
add_interface_port axi4stream_slave axi_rx_tlast tlast Input 1
add_interface_port axi4stream_slave axi_rx_tuser tuser Input 8


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock
set_interface_property avalon_streaming_source associatedReset reset_sink
set_interface_property avalon_streaming_source dataBitsPerSymbol 8
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyAllowance 0
set_interface_property avalon_streaming_source readyLatency 0
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""
set_interface_property avalon_streaming_source IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property avalon_streaming_source SV_INTERFACE_TYPE ""
set_interface_property avalon_streaming_source SV_INTERFACE_MODPORT_TYPE ""

add_interface_port avalon_streaming_source avst_source_ready ready Input 1
add_interface_port avalon_streaming_source avst_source_valid valid Output 1
add_interface_port avalon_streaming_source avst_source_data data Output 96
add_interface_port avalon_streaming_source avst_source_sop startofpacket Output 1
add_interface_port avalon_streaming_source avst_source_eop endofpacket Output 1
add_interface_port avalon_streaming_source avst_source_empty empty Output 4

