# TCL File Generated by Component Editor 23.2
# Fri Aug 04 08:03:45 PDT 2023
# DO NOT MODIFY


# 
# oneAPI_axi4_stream_output_gasket "oneAPI AXI4-Stream Output Gasket" v0.3
# Paul White 2023.08.04.08:03:45
# Allow a oneAPI IP component to output to VVP
# 

# 
# request TCL package from ACDS 23.2
# 
package require -exact qsys 23.2


# 
# module oneAPI_axi4_stream_output_gasket
# 
set_module_property DESCRIPTION "Allow a oneAPI IP component to output to VVP"
set_module_property NAME oneAPI_axi4_stream_output_gasket
set_module_property VERSION 0.3
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP oneAPI
set_module_property AUTHOR "Paul White"
set_module_property DISPLAY_NAME "oneAPI AXI4-Stream Output Gasket"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0
set_module_property PRE_COMP_MODULE_ENABLED false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_to_axi_gasket
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file avst_to_axi_gasket.sv SYSTEM_VERILOG PATH avst_to_axi_gasket.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""
set_interface_property clock IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property clock SV_INTERFACE_TYPE ""
set_interface_property clock SV_INTERFACE_MODPORT_TYPE ""

add_interface_port clock clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""
set_interface_property reset_sink IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property reset_sink SV_INTERFACE_TYPE ""
set_interface_property reset_sink SV_INTERFACE_MODPORT_TYPE ""

add_interface_port reset_sink resetn reset_n Input 1


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clock
set_interface_property avalon_streaming_sink associatedReset reset_sink
set_interface_property avalon_streaming_sink dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyAllowance 0
set_interface_property avalon_streaming_sink readyLatency 0
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""
set_interface_property avalon_streaming_sink IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property avalon_streaming_sink SV_INTERFACE_TYPE ""
set_interface_property avalon_streaming_sink SV_INTERFACE_MODPORT_TYPE ""

add_interface_port avalon_streaming_sink avst_sink_ready ready Output 1
add_interface_port avalon_streaming_sink avst_sink_valid valid Input 1
add_interface_port avalon_streaming_sink avst_sink_data data Input 96
add_interface_port avalon_streaming_sink avst_sink_sop startofpacket Input 1
add_interface_port avalon_streaming_sink avst_sink_eop endofpacket Input 1
add_interface_port avalon_streaming_sink avst_sink_empty empty Input 4


# 
# connection point axi4stream_master
# 
add_interface axi4stream_master axi4stream start
set_interface_property axi4stream_master associatedClock clock
set_interface_property axi4stream_master associatedReset reset_sink
set_interface_property axi4stream_master ENABLED true
set_interface_property axi4stream_master EXPORT_OF ""
set_interface_property axi4stream_master PORT_NAME_MAP ""
set_interface_property axi4stream_master CMSIS_SVD_VARIABLES ""
set_interface_property axi4stream_master SVD_ADDRESS_GROUP ""
set_interface_property axi4stream_master IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property axi4stream_master SV_INTERFACE_TYPE ""
set_interface_property axi4stream_master SV_INTERFACE_MODPORT_TYPE ""

add_interface_port axi4stream_master axi_tx_tready tready Input 1
add_interface_port axi4stream_master axi_tx_tvalid tvalid Output 1
add_interface_port axi4stream_master axi_tx_tdata tdata Output 64
add_interface_port axi4stream_master axi_tx_tlast tlast Output 1
add_interface_port axi4stream_master axi_tx_tuser tuser Output 8

