[project]
name = "modin-gettingstarted"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.1",
    "modin[all]>=0.32.0",
    "notebook>=7.3.2",
]
